export const colorMap = {
  primary: "bg-primary",
  secondary: "bg-secondary",
  tertiary: "bg-tertiary",
  red: "bg-red-500",
  black: "bg-black",
  purple: "bg-purple-700",
  zinc: "bg-zinc-700",
  gray: "bg-gray-700",
  green: "bg-green-500",
  blue: "bg-blue-500",
  orange: "bg-orange-500",
  yellow: "bg-yellow-500",
  pink: "bg-pink-500",
  cyan: "bg-cyan-500",
};
